### ISSUE TITLE
Enable publishing to custom web server (i.e. non-IPFS)

### ISSUE THREAD

**Issue by hiddentao** [solui/solui#17]
Devs should be able to publish the full Dapp to any hosted location (e.g. Github pages). My thinking is that the CLI should be able to spit out the full HTML + Renderer JS + Dapp spec to a local folder from where you can then upload it to your host of choice.

**Comment by ryanio** [comment]
Yes this is exactly what I was thinking, a local build command to get a fully packaged version that anyone could upload to any static site host :) it would provide a lot of flexibility.

**Comment by hiddentao** [comment]
Great. 

Adding some dev notes:

* CLI needs to download the renderer package from IPFS into build folder
* Edit the renderer bootstrap to point to the local artifacts
* Output the spec and artifacts JSON to the build folder

**Comment by hiddentao** [comment]
Done: https://solui.dev/docs/command-line/command:-publish-folder

**Comment by ryanio** [comment]
That was fast! 💯

**Comment by ryanio** [comment]
It looks like there is a typo in the opening sentence: “Use the publish-ipfs command...”

**Comment by hiddentao** [comment]
Thanks, now fixed.
